package blog::Model::myDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'blog::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dbname=blog',
        user => 'root',
        password => '',
    }
);

=head1 NAME

blog::Model::myDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<blog>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<blog::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.5

=head1 AUTHOR

Курьянович Егор

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
